name: {{bloc_name}}_implement
description: A new Flutter project.
version: 0.0.1

publish_to: none

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  clickable: 0.0.11
  flexible: ^1.0.0
  flutter_svg: ^1.1.1+1
  agility_redux_bloc: ^1.0.0
  protobuf: ^2.1.0

  ui_component:
    path: ../../../ui_component

  {{bloc_name}}_interface:
    path: ../{{bloc_name}}_interface

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/image/
    - assets/svg/
  uses-material-design: true